name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'  # Recommended LTS version for Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # Prefer 'stable' over 'beta' for production
          flutter-version: '3.22.0'  # Specify a version for consistency
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter build apk
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
